### ISSUE TITLE
Konfiguration der abzufragenden Parameter 

### ISSUE THREAD

**Issue by OMCastle** [thovid/ioBroker.viessmannapi#12]
Hallo,

nicht jeder Parameter wird von jeder Heizung unterstützt. 
Bitte Konfigurierbar machen oder in dem adapter filtern. 
Reduziert so die Datenpunkte usw. 

Danke

**Comment by thovid** [comment]
Hallo, 

eigentlich werden die Datenpunkte schon so gefiltert, dass nur die für die jeweilige Heizung aktiven Parameter als State angelegt werden. Hast du einen Screenshot oder ähnliches auf dem ich sehen kann, welcher Datenpunkt "zu viel" ist?

**Comment by thovid** [comment]
Closed. Falls noch Fragen offen sind, bitte wieder auf Open setzen.
