### ISSUE TITLE
Steuerung der Heizung

### ISSUE THREAD

**Issue by OMCastle** [thovid/ioBroker.viessmannapi#13]
Ich würde mich über folgende Funktionen freuen.

Aktivieren der Warmwasseraufbereitung für 15 min um einmal den Warmwasserspeicher zu füllen
Änderung der Temperatur für die Heizung
Entweder direkt als Funktionen oder über direktes „schreiben“ der Variablen.

**Comment by thovid** [comment]
Hallo, aus meiner Sicht ist dieser Feature Request mit Version 1.2.0 des Adapters erledigt, daher schließe ich das Issue. Falls noch Fragen oder Wünsche offen sind, einfach wieder auf machen oder neues Issue anlegen.

Grüße Thomas
