### ISSUE TITLE
Künftige Versionen

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#14]
Hallo Thomas,

wird es denn auch eine über NPM zu installierbare Version geben?
Wie erkennt man eigentlich in welcher Version der (benötigte) node-viessmann-api-client
lokal vorliegt und ob er ggf. aktualisiert werden muss?

Derzeit hast Du ja nur die github Version.
![grafik](https://user-images.githubusercontent.com/26110738/51138663-fd1d2f80-1841-11e9-8713-4d32232f185a.png)

Viele Grüße
Fabian

**Comment by thovid** [comment]
Hallo,
die aktuelle Version 1.3.1 (und alle zukünftigen) ist jetzt über NPM installierbar. Wenn es ein Update von node-viessmann-api-client gibt, wird es auch eine neue Version des Adapters geben.

Grüße,
Thomas
