### ISSUE TITLE
Solarpenels from vissmann

### ISSUE THREAD

**Issue by NewTris** [thovid/ioBroker.viessmannapi#22]
Hi I use this adapter and it works very good! 
Thanks a lot for your work. 

I have a question about solarpenal (not electical ony warm water) from vissmann. 
I have some solarpenels on my roof wich are fine connected to the system, and also in the app from vissmann I can see the values how many kw/h are generated. 

Is there a possibliety to add this also to this adapter?

Regards
Christian

**Comment by thovid** [comment]
Hi Christian,

the adapter provides all values that are available from the viessmann server. So, if the value you are looking for is not present, I'm afraid I currently can do nothing to add it.

**Comment by thovid** [comment]
Closing the issue now. If you have more questions, please reopen / create a new issue. Thanks for trying out the adapter :)
