### ISSUE TITLE
Change values by node red or iobroker

### ISSUE THREAD

**Issue by Hamudulu** [thovid/ioBroker.viessmannapi#23]
Hello, thanks for sharing this app with us. I use it and I m happy, but I have the problem to change the values. It always jumbs back after a while to the status before. What can that be? How to solve? Thanks

**Comment by thovid** [comment]
Hi, currently values can not be changed by setting the state. Instead, you need to use the `sendTo` function to execute the appropriate action as described in the README.

**Comment by Hamudulu** [comment]
Yes of course, I tried this like in the Readme. But nothing happend. The temp didn't update. Is there another trick or possible problem?

**Comment by thovid** [comment]
Which version of the adapter are you using? If it is the most recent version, try "Upload Adapter", this has helped others.

**Comment by Hamudulu** [comment]
Version is 1.3.2. I uploaded it, but what does this mean? In the moment the viessmann server is down, so I can't check if it s working now ;-)

**Comment by thovid** [comment]
Were you able to check if it is working now? The upload updates some internal configuration of the adapter - in this particular case this is required so that the adapter is able to receive "messages" sent via the 'sendTo' command.
I'm currently not sure why you need to do the upload manually, I had the hope that this happens automatically when you install a new version...

**Comment by Hamudulu** [comment]
Unfortunately it is not working. Maybe it is required to change a configuration on the vitodens itself? Can it be that the time program need to be off? So the internal time program can not overwrite the changed values? Können wir eigentlich auf Deutsch weiterschreiben?

**Comment by Hamudulu** [comment]
Mein script sieht so aus: 
    sendTo('viessmannapi.0', 'action', {
    feature: 'viessmannapi.0.heating.circuits.0.operating.programs.normal.temperature',
    action: 'setTemperature',
    payload: {targetTemperature: 21}
});
fehlt da was, ist da was zuviel? Erstellt im JS Adapter.

**Comment by mike-bee** [comment]
Hi Hamadulu
I am using the exact same command successfully: feature , action and payload are stings and need to be surrounded by "".

@thovid:
I am trying the following, which is not working:
sendTo("viessmannapi.0", "action", {
           "feature": 'viessmannapi.0.heating.dhw.pumps.circulation.schedule',
           "action":  'setSchedule',
           "payload": {newSchedule: {
                "mon":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "tue":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "wed":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "thu":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "fri":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "sat":[{"start":"05:30","end":"22:00","mode":"on","position":0}],
                "sun":[{"start":"05:30","end":"22:00","mode":"on","position":0}]
                }
            }
        });
I am not sure about the payload syntax. Any hint appreciated.
Thanks
MikeBee

**Comment by thovid** [comment]
@all: sorry for the late reply, was on vacations and had some storm-related issues at home afterwards.

@Hamudulu Soweit ich sehen kann sollte das Feature `'viessmannapi.0.heating.circuits.0.operating.programs.normal'` (ohne `'.temperature'` am Ende) sein.

@mike-bee I do not think, that it is required to enclose the attribute names with `"`, but it should not be a problem to do so. Regarding the Schedule: The syntax looks correct to me. At least in my installation, I do not have a feature named `heating.dhw.pumps.circulation.schedule`, but I have a fature named `heating.dhw.schedule`... Maybe this is the issue?

**Comment by mike-bee** [comment]
Thanks for your reply. Nice job BTW.
I want to stop circulation of 'domestic hot water' while being absent and restart when returning home. I have a brand new Vitodens 333-F and can see three related objects under the adapter:
'viessmannapi.0.heating.dhw.pumps.circulation.schedule.active' (true/false), 'viessmannapi.0.heating.dhw.pumps.circulation.schedule.entries' (schedule) and
'viessmannapi.0.heating.dhw.pumps.circulation.status' (on/off).
Also when querying the features they are listed like that.
I got it working now: I need to use the feature name 'heating.dhw.pumps.circulation.schedule'
If you are interested in updating your documentation let me know and I can provide the details.
I am new to ioBroker and got this working in a few hours. That's really great. Thanks for the good work.
Best
Mike-Bee

**Comment by Hamudulu** [comment]
Thanks mike-bee and also thvoid for your work and informations.

**Comment by cstudener** [comment]
@thovid Thanks for the great work! Listening works perfect for a few days now!

@mike-bee Thats exactly what I'm looking for! Change the state of the circulation pump (and the Water heating) by the need of my house and not the schedule from the heating system. Can you please explain, what parameters you used for action and payload on  'heating.dhw.pumps.circulation.schedule'? Thank you

**Comment by mike-bee** [comment]
**@cstudener** Here you go for both cases:

1. Pump on
```
        /* Restore default Circulation Schedule */
        sendTo("viessmannapi.0", "action", {
           "feature": 'heating.dhw.pumps.circulation.schedule',
           "action":  'setSchedule',
           "payload": {newSchedule: {
                "mon":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "tue":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "wed":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "thu":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "fri":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "sat":[{"start":"06:00","end":"22:00","mode":"on","position":0}],
                "sun":[{"start":"06:00","end":"22:00","mode":"on","position":0}]
                }
            }

```
2. Pump off
```
        /* Erase Circulation Schedule */
        sendTo("viessmannapi.0", "action", {
           "feature": 'heating.dhw.pumps.circulation.schedule',
           "action":  'setSchedule',
           "payload": {newSchedule: {
                "mon":[],
                "tue":[],
                "wed":[],
                "thu":[],
                "fri":[],
                "sat":[],
                "sun":[]
                }
            }

```

Hope that helps.
Mike-Bee

**Comment by cstudener** [comment]
@mike-bee Thank you for this "dirty" trick. It's working for me. I thought there has to be a simple on/off or activate/deactivate command for the circulation, dhw charging and heating instead of the different schedule settings. But anyway, with this trick, it's working :-)
