### ISSUE TITLE
support for solarcolector temperature

### ISSUE THREAD

**Issue by axelrathey** [thovid/ioBroker.viessmannapi#27]
Hi,
I read the following closed issue. As I can't reopen here is a new one about it

https://github.com/thovid/ioBroker.viessmannapi/issues/22

I have viessmann thermal solar panels too. I can see their colector temperature and their storage temperature on my heatpump display and in the old viessmann app Vitotrol Plus as Christian described too. The solar controller ist connected with my viessmann hetpump controler via Viessmann 2wire bus.

![Screenshot_20190328-150007_Vitotrol Plus](https://user-images.githubusercontent.com/26926369/55163656-769e9b80-516a-11e9-8fc1-5ca65f4122d4.jpg)

I do not know the viessmann api for vitotrol but there must be a method to read these temperatures.

Axel

**Comment by thovid** [comment]
Hi Axel,

as written in my comment for #22 : I expose all values I get from the Viessmann server. As I do not have thermal solar panels in my installation, I can not look for myself. If no state created by the adapter matches the value you're looking for, I do not see a way to add the information.

Regards,
Thomas
