### ISSUE TITLE
Rückfrage zur Nutzung

### ISSUE THREAD

**Issue by AlexanderSch90** [thovid/ioBroker.viessmannapi#30]
Hallo, bin mit dem Funktionsumfang voll und ganz glücklich. 

Nutze am meisten die Möglichkeit die WW-Temperatur zu ändern:
Ich habe eine Vitodens 333 WSA Bj 2005 und die WW-Hysterese ist in Verbindung mit dem kleinen WW-Speicher  so schlecht, dass der Brenner mehrmals am Tag startet um WW zu produzieren. 

Ich senke also nun nach dem WW-Aufbereiten die WW-Temperatur auf 40 Grad und erhöhe diese im Moment der WW-Aufbereitung auf 60 Grad. Somit erweitere ich die WW-Hysterese und verhindere unnötige Brennerstarts. 

Jetzt habe ich durch zufall mitbekommen, dass dies wahrscheinlich eher keine gute Idee ist: 
Ich habe gelesen, dass die Werte ggf. oder wahrscheinlich in einem EEPROM gespeichert werden. Dieser ist denke ich nicht dafür ausgelegt, sodass mir ein Platinenschaden droht?! Wenn dies so ist würde ich das ganze für mich wieder rückgängig machen. Vielleicht ist hier ja ein versierter Viessmann Heizungsbauer oder Elektriker, der das aufklären könnte... 

Ggf. könnte man dies dann als Hinweis aufnehmen. Sodass die Nutzer nicht zu oft am Tag Werte "schreiben" sondern sich auf das auslesen konzentrieren...

Vielen Dank für den geilen Adapter.

**Comment by thovid** [comment]
Hallo,
danke für das tolle Feedback. Wie die Speicherung der Einstellungen bei den verschiedenen Heizungstypen realisiert ist weiß ich leider nicht.

Ich überlege mal, wie ich einen entsprechenden Warnhinweis in die README aufnehmen kann.

Danke und Grüße,
Thomas
