### ISSUE TITLE
Warmwassertemperatur

### ISSUE THREAD

**Issue by MichaDebuss** [thovid/ioBroker.viessmannapi#32]
Hallo,

erstmal großes Kompliment zu dem Adapter. Echt klasse!

Habe eine Frage:
Wie kann ich die Wassertemperatur abfragen? Das habe ich noch nicht rausgefunden.

Vielen Dank im Voraus für jede Antwort.

Gruß

Micha Debuss

**Comment by thovid** [comment]
Hallo,

falls du Wassertemperatur für die Warmwasserbereitung meinst, die ist bei mir unter `heating.dhw.temperature.value` zu finden. 
Die Boiler Temperatur der Heizung ist unter `heating.boiler.temperature.value` zu finden.

Hoffe, das hilft.
Grüße
Thomas

**Comment by MichaDebuss** [comment]
Hallo Thomas. 

Vielen Dank. Das hilft mir weiter. 

Gruß Micha
