### ISSUE TITLE
Betriebsart ändern

### ISSUE THREAD

**Issue by MichaDebuss** [thovid/ioBroker.viessmannapi#33]
Hallo zusammen,

Adapter läuft soweit sehr gut bei mir. Temperatur abfragen usw... klappt einwandfrei.
Was mir noch nicht ganz klar ist, **wie kann die Betriebsart geändert werden?**

z.B. von "Heizung und Warmwasser aktiv" (Parameter dhwAndHeating) auf "Nur Warmwasser aktiv" (Parameter dwh) .

Habe es mit SentTo probiert, irgendwie klappt es noch nicht:

`sendTo('viessmannapi.0', 'action', {
    feature: 'operating.modes.active',
    action: 'setMode',
    payload: {mode: dhw}
});`

Was mache ich falsch? 

Wäre super, wenn mir jemand helfen könnte.

Vielen Dank im Voraus.

Gruß

Micha Debuss

**Comment by thovid** [comment]
Hi, versuch `heating.circuits.0.operating.modes.active` als Wert bei `feature`.

Grüße,
Thomas

**Comment by MichaDebuss** [comment]
Hallo Thomas,

perfekt. Genau das war es. :-)

Vielen Dank für deine Unterstützung!

Gruß

Micha
