### ISSUE TITLE
Adapter startet nicht mehr

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#34]
Hallo Thomas,

seit dieser Nacht läst sich der Adapter nicht mehr starten. Im Log tritt folgender Error auf:
![grafik](https://user-images.githubusercontent.com/26110738/59500195-3b725580-8e99-11e9-9ba2-8a5b43b4e318.png)

Da ich am System nichts geändert habe kann ich den Error leider überhaupt nicht nachvollziehen.
Woran könnte es liegen?
Grüße
Fabian

**Comment by thovid** [comment]
Hallo Fabian,

ich werde mir das heute Abend anschauen können. 

Grüße,
Thomas

**Comment by Hamudulu** [comment]
Hallo
Gibts da neue Erkenntnisse? Mein Adapter ist auch schon länger offline und startet nicht mehr...
Grüße

**Comment by Hamudulu** [comment]
Ok, komplett deinstallieren und wieder installieren hat geholfen....warum auch immer...
