### ISSUE TITLE
change object status from on/off to true/false

### ISSUE THREAD

**Issue by createch2** [thovid/ioBroker.viessmannapi#37]
Would it make sense to change the object status from on / off to boolean true / false ?
This would give us a better way to handle the object status in programs or Foot diagrams.
Currently I need to have a workaround through a second variable and a script that translates it to boolean type.

**Comment by thovid** [comment]
The adapter just exposes the values received from the Viessmann-server without any transformation. Thus, if the server sends on / off, the adapter will not change this...
