### ISSUE TITLE
keine Steuerung mit Iobroker 

### ISSUE THREAD

**Issue by Micha996** [thovid/ioBroker.viessmannapi#39]
Hallo, ich habe den Adapter installiert, unter Iobroker ist er grün. Die Werte meiner Heizung werde auch angezeigt aber ich kann Sie nicht ändern.. Ich habe den Adapter auf debug geschalten folgende Fehlermeldung bekomme ich .. 

OAuthClient:  GET  https://api.viessmann-platform.io/operational-data/installations/48419/gateways/757138443t300/devices/0/features  - payload undefined
--
viessmannapi.0 | 2019-10-12 16:11:45.182 | debug | ViessmannClient: polling for updates...

**Comment by FabianHM** [comment]
Du kanst bestimmte Werte ändern, jedoch nur über die sendTo Methode.
Beispiel:
```
"sendTo('viessmannapi.0', 'action', {
    feature: 'heating.circuits.0.operating.programs.comfort',
    action: 'setTemperature',
    payload: {targetTemperature: 20}
});
```
