### ISSUE TITLE
Error fetching features: Request failed with status 404

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#41]
Hallo Thomas,
in den letzten Tagen fällt mir oft eine Fehlermeldung auf, die bisher nie erschien.
`"(2431) ViessmannClient: error fetching features: Request failed with status 404"`

Kann es evtl. mit dem neuen JS Controler 2.x zusammen hängen?
Grüße
Fabian

**Comment by Ilovegym66** [comment]
Anscheinend kann der Adapter keinen neuen Token mehr holen, wenn der alte Abgelaufen ist..??

**Comment by FabianHM** [comment]
Der  `Request failed with status 404` ist nicht mehr aufgetreten, daher schließe ich diesen Issue
