### ISSUE TITLE
Partymodus

### ISSUE THREAD

**Issue by AlexanderSch90** [thovid/ioBroker.viessmannapi#44]
Hallo, danke für den super Adapter!

Ist es möglich im Iobroker die "Partytaste" zu drücken?
Wenn ja wo ist diese Funktion versteckt ;-)

Danke!

Alternativ baue ich mir ein Skript, welches die Modis tauscht: heating.circuits.X.operating.modes.active

dhwandheating zu Forcednormal und zurück...

Viele Grüße

**Comment by thovid** [comment]
Hallo, ich habe in den Features, die der Server zurück gibt keinen Party-Modus gefunden. D.h. ich würde es über deine Skript Idee bauen.
Grüße

**Comment by FabianHM** [comment]
> 
> 
> Hallo, danke für den super Adapter!
> 
> Ist es möglich im Iobroker die "Partytaste" zu drücken?
> Wenn ja wo ist diese Funktion versteckt ;-)
> 
> Danke!
> 
> Alternativ baue ich mir ein Skript, welches die Modis tauscht: heating.circuits.X.operating.modes.active
> 
> dhwandheating zu Forcednormal und zurück...
> 
> Viele Grüße

Partymodus entspricht Komfortmodus.
Zitat Viessmann Forum:
> "Die Schnellwahl "Partymodus" ist in Android unter "Komfortmodus" zu finden.
> Sie endet entweder nach 8 Stunden oder geht bis zur nächsten Schaltzeit."

Bei mir erledigt es ein Button des ioBroker in VIS

**Comment by thovid** [comment]
Dank der Antwort von Fabian betrachte ich das Issue als Closed.
