### ISSUE TITLE
Error | Unhandled  promise rejection -> Kein Login mehr möglich

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#55]
Hallo Thomas,

in den letzten Tagen meldete die Viessmann App Wartungen im Backend.
Der Adapter wird leider nicht mehr grün. Evtl besteht ein Zusammenhang?
Meine zugangsdaten habe ich auf der Viessmann Homepage gecheckt, Zugrifff funktioniert dort.

Hier mal die neuerlichen Debug Meldungen des Adapters:
` viessmannapi.0 | 2020-08-09 13:09:54.058 | info | (8678) ViessmannClient: initializing with pollIntervall 300000
-- | -- | -- | --
viessmannapi.0 | 2020-08-09 13:09:54.029 | info | (8678) starting adapter...
viessmannapi.0 | 2020-08-09 13:09:53.999 | info | (8678) starting. Version 1.3.3 in /opt/iobroker/node_modules/iobroker.viessmannapi, node: v12.18.3, js-controller: 3.1.6
viessmannapi.0 | 2020-08-09 13:09:21.501 | info | (8663) Terminated (NO_ERROR): Without reason
viessmannapi.0 | 2020-08-09 13:09:21.500 | info | (8663) terminating
viessmannapi.0 | 2020-08-09 13:09:21.490 | error | (8663) TypeError: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'     \|     property '_httpMessage' -> object with constructor 'ClientRequest'     --- pro
viessmannapi.0 | 2020-08-09 13:09:21.489 | error | (8663) unhandled promise rejection: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'     \|     property '_httpMessage' -> object with constructor 'ClientRe
viessmannapi.0 | 2020-08-09 13:09:21.488 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
viessmannapi.0 | 2020-08-09 13:09:21.281 | debug | (8663) OAuthClient: requesting initial access token using refreshToken=undefined
viessmannapi.0 | 2020-08-09 13:09:21.280 | debug | (8663) OAuthClient: initializing client`

Aktuell verwendete Version ist 1.3.3

Könntest Du bitte mal schauen,

Danke und Grüße
Fabian

**Comment by FabianHM** [comment]
Nach mehreren Neustarts des Systems wurde nun wieder ein Token erzeugt und eine Verbindung aufgebaut.
Ich schließe den Issue zunächst, beobachte das Thema aber mal nebenbei.

Grüße
Fabian

**Comment by thovid** [comment]
Danke für's melden bzw weiter beobachten.
Gruß Thomas
