### ISSUE TITLE
Adapter hat häufig keine Connection

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#59]
Hallo Thomas,

mir sind in der letzten Zeit viele Verbnidungsabbrüche (Version 1.3.3) aufgefallen mit Fehlemeldungen die mir bisher unbekannt sind.
Zu den Zeitpunkten ist jedoch über die Website Zugriff auf die API möglich.
Somit kann ich zumindest die mittlwerwile häufigen Wartungsarbeiten von Viessmann bzw. WLAN Probleme ausschließen.

viessmannapi.0 | 2020-10-12 18:22:36.420 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | at rejected (/opt/iobroker/node_modules/iobroker.viessmannapi/dist/main.js:6:65)
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | at Generator.throw (<anonymous>)
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | at /opt/iobroker/node_modules/iobroker.viessmannapi/dist/main.js:169:47
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | at JSON.stringify (<anonymous>)
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | --- property 'socket' closes the circle
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | \|     property '_httpMessage' -> object with constructor 'ClientRequest'
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | --> starting at object with constructor 'TLSSocket'
viessmannapi.0 | 2020-10-12 18:22:36.420 | error | (20201) TypeError: Converting circular structure to JSON
viessmannapi.0 | 2020-10-12 18:22:36.419 | error | --- property 'socket' closes the circle
viessmannapi.0 | 2020-10-12 18:22:36.419 | error | \|     property '_httpMessage' -> object with constructor 'ClientRequest'
viessmannapi.0 | 2020-10-12 18:22:36.419 | error | --> starting at object with constructor 'TLSSocket'
viessmannapi.0 | 2020-10-12 18:22:36.419 | error | (20201) unhandled promise rejection: Converting circular structure to JSON
Unhandled | 2020-10-12 18:22:36.419 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

und nun dauerhaft:

`

viessmannapi.0 | 2020-10-12 18:27:37.307 | error | (20400) TypeError: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'     \|     property '_httpMessage' -> object with constructor 'ClientRequest'     --- pr
-- | -- | -- | --
viessmannapi.0 | 2020-10-12 18:27:37.306 | error | (20400) unhandled promise rejection: Converting circular structure to JSON     --> starting at object with constructor 'TLSSocket'     \|     property '_httpMessage' -> object with constructor 'ClientR
viessmannapi.0 | 2020-10-12 18:27:37.305 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

`

Könntest Du vielleicht einen Blick darauf werfen?
Danke und LG
Fabian

**Comment by Ilovegym66** [comment]
hier leider auch, genauso.

**Comment by FabianHM** [comment]
> 
> 
> hier leider auch, genauso.

Kannst Du mal testen ob der Zugiff auf die Web-API bei Dir gerade auch funktioniert? Bei mir zumindest einwandfrei:
https://vitoguide.viessmann.com/

**Comment by Ilovegym66** [comment]
Ja, läuft.

**Comment by thovid** [comment]
Ich schaue es mir an

**Comment by JayVee2** [comment]
Ich kann die Fehlermeldungen bestätigen. Mit Eingeben der Login-Daten war meist wieder ein Zugriff möglich.

Über das Wochenende hat Viessmann wohl größere Serverumstellungen vorgenommen, zumindest hat das meine ViCare App behauptet, wenn sie zwischendurch überhaupt durchkam.

Jetzt scheint auf Viessmann-Seite wieder alles zu laufen. ViCare geht bei mir, keine Nachrichten von Viessmann mehr, die auf Probleme hinweisen.

https://vitoguide.viessmann.com/ geht auch.

Der Adapter allerdings scheint gar nicth mehr zu gehen und produziert konsequent einen 404-Fehler. X-mal Passwort neu eingegeben und Adapter neu gestartet.

Ist es möglich, dass Viessmann irgendwas ander Serveradresse geändert hat?
Merkwürdig ist, dass Links aus meiner Word Dokument auf https://vitoguide.viessmann.com/home ebenfalls einen 404 Fehler produzieren, derselbe Link aber vom Forum aus geht.

Grüße

-jayvee

**Comment by Hamudulu** [comment]
Same problem here...Error code 404

**Comment by thovid** [comment]
Ja, bei mir auch. Sieht wie von @JayVee2 vermutet danach aus, als hätte sich bei Viessmann irgendeine url geändert...

**Comment by thovid** [comment]
Hm, nach Neustart des Adapters (und neuer Eingabe der Logindaten) geht es wieder. Viessmann scheint die Änderung, die gestern zu der Störung geführt hat, zurückgenommen.

**Comment by JayVee2** [comment]
Kann ich bestätigen.

**Comment by FabianHM** [comment]
> 
> 
> Hm, nach Neustart des Adapters (und neuer Eingabe der Logindaten) geht es wieder. Viessmann scheint die Änderung, die gestern zu der Störung geführt hat, zurückgenommen.

Kann ich ebenfalls bestätigen
Danke an alle für die Beteiligung bei der Fehlersuche
