### ISSUE TITLE
Login to api not possible since 11.10.2020 (again api restrictions after maintenance job)?

### ISSUE THREAD

**Issue by tminimax** [thovid/ioBroker.viessmannapi#60]
Hi,
since a few days the ioBroker.viessmannapi can not connect to the cloud any more. I checked the credentials and also i deinstalled and installed the adapter again. The ViCare App on the mobile phone is still working, but it reported on sunday (=11.10) that due to maintenance work some features may not work. So i think that they have changes again something on the api...

Here is the log content:
![grafik](https://user-images.githubusercontent.com/72692458/95882262-c60ee180-0d79-11eb-911b-6f053198ba53.png)

viessmannapi.0 | 2020-10-13 17:19:29.973 | error | (3451) could not connect using email and password, check credentials!
viessmannapi.0 | 2020-10-13 17:19:29.970 | error | (3451) _**error connecting: {"status":502}**_

In the instances view the adapter is yellow marked 
![grafik](https://user-images.githubusercontent.com/72692458/95882462-040c0580-0d7a-11eb-829e-1b7f66425a4f.png)
connected to host = TRUE; alive = TRUE; connected to viessmann api = FALSE

Does anyone else has the same problem? Any ideas?

Thank you

**Comment by thovid** [comment]
I just checked the status of my adapter, it's green & connected. Yesterday there were some issues resulting in a longer downtime. Does the issue persist? If yes, could you try to set the adapter's loglevel to 'debug' (can be done on the instances view if you enable expert mode) and post the logs?

Thomas

**Comment by tminimax** [comment]
Hi Thomas,
after switching to your suggested loglevel "debug" the adapter restartet and now everything is green (for the moment). I do not unterstand it....some "payload undefind" mesages..
**_Log:_**

viessmannapi.0 | 2020-10-13   21:20:45.601 | debug | (3702) system.adapter.admin.0: logging true
-- | -- | -- | --
viessmannapi.0 | 2020-10-13   21:19:35.453 | debug | (3702) system.adapter.admin.0: logging false
viessmannapi.0 | 2020-10-13   21:18:56.044 | debug | (3702)   Scheduler started
viessmannapi.0 | 2020-10-13   21:18:55.964 | info | (3702) ViessmannClient: initialized with   installation={"installationId":"****","gatewayId":"*****","deviceId":"0"}
viessmannapi.0 | 2020-10-13   21:18:55.263 | debug | (3702) OAuthClient: GET   https://api.viessmann-platform.io/operational-data/installations/*****/gateways/*****/devices/0/features   - payload undefined
viessmannapi.0 | 2020-10-13   21:18:54.774 | debug | (3702) OAuthClient: GET   https://api.viessmann-platform.io/general-management/installations - payload   undefined
viessmannapi.0 | 2020-10-13   21:18:54.770 | debug | (3702) ViessmannClient: requesting installation details during   initialization
viessmannapi.0 | 2020-10-13   21:18:54.142 | debug | (3702) OAuthClient: requesting initial access token using refreshToken=****
viessmannapi.0 | 2020-10-13   21:18:54.138 | debug | (3702)   OAuthClient: initializing client
viessmannapi.0 | 2020-10-13   21:18:54.133 | info | (3702)   ViessmannClient: initializing with pollIntervall 900000
viessmannapi.0 | 2020-10-13   21:18:54.129 | info | (3702)   authenticating with refresh token
viessmannapi.0 | 2020-10-13   21:18:53.776 | info | (3702)   starting adapter...
viessmannapi.0 | 2020-10-13   21:18:53.651 | info | (3702) starting. Version 1.3.3 in   /opt/iobroker/node_modules/iobroker.viessmannapi, node: v10.22.1,   js-controller: 3.1.6
viessmannapi.0 | 2020-10-13   21:18:53.011 | debug | (3702)   statesDB connected
viessmannapi.0 | 2020-10-13   21:18:53.008 | debug | (3702) States   connected to redis: 127.0.0.1:9000
viessmannapi.0 | 2020-10-13   21:18:52.986 | debug | (3702) States create System PubSub Client
viessmannapi.0 | 2020-10-13   21:18:52.977 | debug | (3702) States create User PubSub Client
viessmannapi.0 | 2020-10-13   21:18:52.958 | debug | (3702) Redis States: Use Redis connection: 127.0.0.1:9000
viessmannapi.0 | 2020-10-13   21:18:52.948 | debug | (3702)   objectDB connected
viessmannapi.0 | 2020-10-13   21:18:52.916 | debug | (3702)   Objects connected to redis: 127.0.0.1:9001
viessmannapi.0 | 2020-10-13   21:18:52.872 | debug | (3702) Objects client initialize lua scripts
viessmannapi.0 | 2020-10-13   21:18:52.868 | debug | (3702) Objects create User PubSub Client
viessmannapi.0 | 2020-10-13   21:18:52.864 | debug | (3702) Objects create System PubSub Client
viessmannapi.0 | 2020-10-13   21:18:52.806 | debug | (3702) Objects client ready ... initialize now
viessmannapi.0 | 2020-10-13   21:18:52.515 | debug | (3702) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.SmartMeter | 2020-10-13   21:18:46.796 | info | instance system.adapter.viessmannapi.0 started with pid 3702
host.SmartMeter | 2020-10-13   21:18:44.289 | info | instance system.adapter.viessmannapi.0 terminated with code 11   (ADAPTER_REQUESTED_TERMINATION)
viessmannapi.0 | 2020-10-13   21:18:44.106 | debug | (3686) OAuthClient: GET   https://api.viessmann-platform.io/operational-data/installations/*****/gateways/****/devices/0/features   - payload undefined
viessmannapi.0 | 2020-10-13   21:18:43.734 | info | (3686) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
viessmannapi.0 | 2020-10-13   21:18:43.729 | info | (3686)   terminating
viessmannapi.0 | 2020-10-13   21:18:43.723 | info | (3686) Got terminate signal TERMINATE_YOURSELF
host.SmartMeter | 2020-10-13   21:18:43.713 | info | stopInstance system.adapter.viessmannapi.0 send kill signal
host.SmartMeter | 2020-10-13   21:18:43.708 | info | stopInstance system.adapter.viessmannapi.0 (force=false, process=true)
viessmannapi.0 | 2020-10-13   21:18:43.563 | debug | (3686) OAuthClient: GET https://api.viessmann-platform.io/general-management/installations   - payload undefined
viessmannapi.0 | 2020-10-13   21:18:43.544 | debug | (3686) ViessmannClient: requesting installation details during   initialization
viessmannapi.0 | 2020-10-13   21:18:42.901 | debug | (3686) OAuthClient: requesting initial access token using refreshToken=***
viessmannapi.0 | 2020-10-13   21:18:42.897 | debug | (3686)   OAuthClient: initializing client
viessmannapi.0 | 2020-10-13   21:18:42.891 | info | (3686)   ViessmannClient: initializing with pollIntervall 900000
viessmannapi.0 | 2020-10-13   21:18:42.887 | info | (3686)   authenticating with refresh token
viessmannapi.0 | 2020-10-13   21:18:42.882 | info | (3686) found email and password in configuration, deleting it due to   security reasons. Adapter should restart now
viessmannapi.0 | 2020-10-13   21:18:42.572 | info | (3686)   starting adapter...
viessmannapi.0 | 2020-10-13   21:18:42.481 | info | (3686) starting. Version 1.3.3 in   /opt/iobroker/node_modules/iobroker.viessmannapi, node: v10.22.1,   js-controller: 3.1.6
viessmannapi.0 | 2020-10-13   21:18:41.772 | debug | (3686)   statesDB connected
viessmannapi.0 | 2020-10-13   21:18:41.769 | debug | (3686) States   connected to redis: 127.0.0.1:9000
viessmannapi.0 | 2020-10-13   21:18:41.746 | debug | (3686) States create System PubSub Client
viessmannapi.0 | 2020-10-13   21:18:41.737 | debug | (3686) States create User PubSub Client
viessmannapi.0 | 2020-10-13   21:18:41.718 | debug | (3686) Redis States: Use Redis connection: 127.0.0.1:9000
viessmannapi.0 | 2020-10-13   21:18:41.708 | debug | (3686)   objectDB connected
viessmannapi.0 | 2020-10-13   21:18:41.677 | debug | (3686)   Objects connected to redis: 127.0.0.1:9001
viessmannapi.0 | 2020-10-13   21:18:41.632 | debug | (3686) Objects client initialize lua scripts
viessmannapi.0 | 2020-10-13   21:18:41.629 | debug | (3686) Objects create User PubSub Client
viessmannapi.0 | 2020-10-13   21:18:41.625 | debug | (3686) Objects create System PubSub Client
viessmannapi.0 | 2020-10-13   21:18:41.606 | debug | (3686) Objects client ready ... initialize now
viessmannapi.0 | 2020-10-13   21:18:41.441 | debug | (3686) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.SmartMeter | 2020-10-13   21:18:35.701 | info | instance system.adapter.viessmannapi.0 started with pid 3686
host.SmartMeter | 2020-10-13   21:18:33.237 | info | instance system.adapter.viessmannapi.0 terminated with code 11   (ADAPTER_REQUESTED_TERMINATION)
viessmannapi.0 | 2020-10-13   21:18:32.672 | info | (3451) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
viessmannapi.0 | 2020-10-13   21:18:32.668 | info | (3451)   terminating
viessmannapi.0 | 2020-10-13   21:18:32.658 | info | (3451) Got terminate signal TERMINATE_YOURSELF
host.SmartMeter | 2020-10-13   21:18:32.647 | info | stopInstance system.adapter.viessmannapi.0 send kill signal
host.SmartMeter | 2020-10-13   21:18:32.641 | info | stopInstance system.adapter.viessmannapi.0 (force=false, process=true)

Is there anything unusual in the log now?
Thank you (anyway) for your fast response...
Thomas

**Comment by thovid** [comment]
Looks ok to me. I'll keep the issue open for a couple of days in case you experience connectivity issues again.

**Comment by tminimax** [comment]
läuft jetzt soweit wieder - danke - auch im zurückgestellten "info" log modus.
Kann man das "verbunden mit viessman api" irgendwie abfragen? ist das die variable "viessmannapi.0.info.connection"?

**Comment by thovid** [comment]
> Kann man das "verbunden mit viessman api" irgendwie abfragen? ist das die variable "viessmannapi.0.info.connection"?

Ja, genau.

Ich schließe das Issue, wenn erneut Probleme auftreten gerne ein neues aufmachen.
