### ISSUE TITLE
Adapter gibt Fehler aus/verbindet sich nicht mehr

### ISSUE THREAD

**Issue by SoldierOc** [thovid/ioBroker.viessmannapi#69]
Hallo Zusammen,

seit gestern Abend bzw. Heute Nacht verbindet sich der Adapter bei mir, trotz korrekter Login-Daten nicht mehr. Auch ein stoppen/neu eintragen der Daten/erneutes Starten führt nur zu Fehlermeldungen.

An meiner Konfiguration im ioBroker (auch Updates o.ä.) hat sich in den letzten Tagen nichts geändert.
Ist dies bei mir ein lokales Problem oder allgemeiner Art?

![image](https://user-images.githubusercontent.com/63428971/120289670-d3a1b900-c2c1-11eb-95ee-708d927ea7c3.png)

Viele Grüße

**Comment by diomedesX** [comment]
Moin, ich habe exakt das gleiche Problem.

**Comment by SoldierOc** [comment]
Konnte es mittlerweile lösen. 
Habe den Adapter komplett gelöscht, inkl. aller Datenpunkte & neu angelegt - nun läuft es problemlos. Weshalb das Problem auch immer auftritt bzw. auftrat...

**Comment by diomedesX** [comment]
> 
> 
> Konnte es mittlerweile lösen.
> Habe den Adapter komplett gelöscht, inkl. aller Datenpunkte & neu angelegt - nun läuft es problemlos. Weshalb das Problem auch immer auftritt bzw. auftrat...

Moin, besten Dank! Das hat geholfen!
