### ISSUE TITLE
Neue Funktion: Gas/Ölverbrauch und Betriebsstunden

### ISSUE THREAD

**Issue by Ilovegym66** [thovid/ioBroker.viessmannapi#7]
Hi, danke für die Arbeit, toll! Adapter läuft ohne Fehler auf Anhieb!
Super wäre es, wenn, da der Wert "Brenner on/off" ja geliefert wird, noch gleich die Betriebsstunden und der Verbrauch von Gas/Öl ausgerechnet werden könnte, so wie hier das Script für HM macht:
https://smart-wohnen.org/homematic-verbrauchs-und-betriebsstundenzaehler-fuer-oelheizungen/?fbclid=IwAR0CYFoED8GcymnswzDJCuDTesqtuY-jlMV8Xy_IPgwDnJ3qH1_2svfc13g

Es werden die Daten der Düse (Durchflussmenge) und bei Öl der vorhandene Tankinhalt (um den restlichen Tankinhalt zu berechnen) benötigt.

**Comment by thovid** [comment]
Hi, danke für das Feedback. Ich schaue mir das verlinkte Script bei Gelegenheit mal an. Könnte man die Berechnung nicht auch in einem eigenen Script machen, wenn man die entsprechenden States subscribed?

**Comment by FabianHM** [comment]
Ich denke wenn der Brennerstatus, also AN oder AUS, ausgegeben wird, ermöglicht dies eigene Berechnungen sehr leicht.

**Comment by mamoel666** [comment]
Wenn man die Brennerstunden direkt auslesen kann - was mit vcontrold möglich ist - kann man das Polling entsprechend verringern. Außerdem muss man sich keine Sorgen machen, falls der ioBroker mal neu aufgesetzt werden muss. Ich denke für die Mehrzahl der User dürften die Brennerstunden das k.o.-Kriterium sein. Denn das Interessanteste an der Heizung ist doch der Brennstoffverbrauch.

**Comment by thovid** [comment]
Der Adapter liefert nur genau das, was Viessmann über seinen Server zur Verfügung stellt. Zumindest bei meiner Heizung habe ich da keine Brennerbetriebsstunden oder ähnliches gefunden. Ihr könnt mal schauen, ob ihr einen state `heating.burner.statistics` habt, und ob da etwas sinnvolles drin steht...
Im Übrigen gebe ich euch recht, mit einem vertretbaren Polling-Wert lassen sich die Betriebsstunden nicht sinnvoll berechnen, da ist die Unschärfe zu groß.

**Comment by mamoel666** [comment]
Warum Viessmann so etwas macht (bzw. nicht macht) ist mir absolut unverständlich. Die Vicare App ist leider total nutzlos. Dass die Brennerstunden über das mitgelieferte Kabel auslesbar sind, aber nicht über die API ausgegeben werden ist für mich ein Armutszeugnis.
Jetzt steht leider weiterhin ein Raspberry samt USB-WLAN-Adapter auf meinem Heizkessel.

**Comment by thovid** [comment]
Die gewünschte Funktion kann ich leider so nicht unterstützen. Bei Gasheizungen gibt es (je nach Heizung?) die States `heating.gas.consumption.heating.*`, die den durch die Heizung ermittelten Verbrauch enthalten. Ob es etwas vergleichbares bei anderen Heizungen gibt kann ich nicht sagen (Test Hardware wäre etwas teuer und aufwändig ;-) ). Ich schließe dieses Issue daher. Falls noch Diskussionsbedarf besteht, einfach wieder öffnen.

Grüße,
Thomas

**Comment by FabianHM** [comment]
Die Brennerstunden und Brennerstarts werden mittlerweile von Viessmann auch übertragen.
