### ISSUE TITLE
Request failed with status 404

### ISSUE THREAD

**Issue by OberfragGER** [thovid/ioBroker.viessmannapi#74]
Moin,
erstmal vielen Dank dass du den Adapter wieder lauffähig gemacht hast.

Ich habe seit vorhin alle 5 Minuten folgendes im Log:
`
viessmannapi.0 | 2021-08-18 11:16:02.819 | error | Error: Request failed with status code 404
-- | -- | -- | --
viessmannapi.0 | 2021-08-18 11:16:02.819 | error | https://api.viessmann.com/iot/v1/equipment/installations/176885/gateways/7571381727470201/devices/$id/features
`

Die letzten Objektaktualisierungen scheinen von heute morgen 8:26 zu sein. Deaktivierung der Instanz und Aktivierung hat nicht gebracht. Instanz ist zwar auf grün, aber weiter die Fehlermeldung(en).

**Comment by ckoeber83** [comment]
![image](https://user-images.githubusercontent.com/52466072/129895423-b858a0aa-91b0-4b17-95dd-e8f321cdcc6e.png)
Es gibt geplante Wartungsarbeiten an den Viessmann-Servern am 19.08.21 22:00 bis 20.08.21 00:00. Während dieser Zeit kann es zu einer Einschränkung der ViCare App-Funktionalität kommen. Diese Wartung hat keine Auswirkung auf Ihr Viessmann Heizsystem. Es dient dazu unsere Server und damit auch Ihre ViCare App zu verbessern.

**Comment by OberfragGER** [comment]
> ![image](https://user-images.githubusercontent.com/52466072/129895423-b858a0aa-91b0-4b17-95dd-e8f321cdcc6e.png)
> Es gibt geplante Wartungsarbeiten an den Viessmann-Servern am 19.08.21 22:00 bis 20.08.21 00:00. Während dieser Zeit kann es zu einer Einschränkung der ViCare App-Funktionalität kommen. Diese Wartung hat keine Auswirkung auf Ihr Viessmann Heizsystem. Es dient dazu unsere Server und damit auch Ihre ViCare App zu verbessern.

Mhh. Wollen wir mal hoffen dass es damit zusammenhängt. Heute ist ja der 18.08..

**Comment by ckoeber83** [comment]
Ich kann auch nach wie vor auf meine API zugreifen
https://api.viessmann-platform.io/iot/v1/equipment/installations/145943/
Ggf mal in der Instanz die Anmeldedaten neu schreiben, oder den Adpater gar neu installieren von 
Github: https://github.com/TA2k/ioBroker.viessmannapi
Forum iobroker: https://forum.iobroker.net/topic/46778/test-viessmannapi-v2-0-0

**Comment by OberfragGER** [comment]
Ich habe soeben folgendes getan:
Instanz gelöscht
Alle Objkete gelöscht
Adapter deinstalliert
Adapter (Version 2.0.1) neu installiert
Neue Instanz angelegt
Neue ClientID erzeugt.

-> Gleicher Fehler:
`viessmannapi.0 | 2021-08-18 17:28:20.023 | error | Error: Request failed with status code 404
-- | -- | -- | --
viessmannapi.0 | 2021-08-18 17:28:20.022 | error | https://api.viessmann.com/iot/v1/equipment/installations/176885/gateways/7571381727470201/devices/$id/features`

**Comment by OberfragGER** [comment]
Oooh. Mein Fehler.

Ich habe gerade Testweise mal die App aufgerufen: "Anlage nicht verbunden".
Laut LEDs an der ANlage war das Ding aber komplett grün.

Stecker raus.. Stecker rein. Läuft.
