### ISSUE TITLE
Neue Konfiguration: Parameter für Aktualisierungsintervall

### ISSUE THREAD

**Issue by FabianHM** [thovid/ioBroker.viessmannapi#9]
Hallo,
es wäre sinnvoll die aktuell verdrahteten 60sec. parametrisierbar zu machen im Reiter Konfiguration.
Ich denke die Aktualisierung sollte je nach Bedarf sein.

**Comment by thovid** [comment]
Ja, ist eingeplant.

**Comment by FabianHM** [comment]
Hallo Thomas,

kannst Du schon absehen wann es das Feauture "Parameter für Aktualisierungsintervall" geben wird?
Ich bin wirklich von der Stabilität des Adapters begeistert und dieses Intervall ist derzeit halt noch etwas häufig, weswegen mich diese Erweiterung noch interessieren würde.

Viele Grüße
Fabian
